
on: push
name: Deplay website on push

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: wheatley.cs.up.ac.za
        username: u24648826
        password: Ilovehockey!27
        protocol: ftp  # change to 'sftp' if needed
        local-dir: ./  # path to the folder you want to upload
        server-dir: /COS221/GithubActions/  # remote path where files should go
